name: Artifact

on: [push]

env:
  ARTIFACT_NAME: myartifact

jobs:
  testartifact:
    runs-on: ubuntu-latest
    steps:
      - name: to checkout
        uses: actions/checkout@v2

      - name: to upload Artifact
        uses: actions/upload-artifcat@v2
        with:
          name: $ARTIFACT_NAME
          path: .