name: first

on: push

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
    - name: step one in job1
      uses: actions/checkout@v2
    - name: step two in job1
      run: env | sort

  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
    - name: step one
      uses: actions/checkout@v2
    - name: step two
      run: "Get-ChildItem Env: | Sort-Object Name"