name: first

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: date
  windows:
    runs-on: windows-latest
    steps:
    - run: date
  mac:
    runs-on: macos-latest
    steps:
    - run: date
  dep:
    needs: [ubuntu,windows,mac]
    runs-on: ubuntu-latest
    steps:
    - run: date